name: Pull Request Comment Trigger
on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Example
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Test
        shell: bash
        run: git log

      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'ci'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'

      - uses: actions/checkout@v1
      - run: ' run'